global:
  scrape_interval: 5s # How often to scrape targets by default.

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['client-backend:8181'] # Replace with your Spring Boot container name and port.
     # - targets: ['localhost:8181'] # Replace with your Spring Boot container name and port.
    metrics_path: '/actuator/prometheus'

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]